### PR TITLE
The local store will create the child directory from root_dir if it doesn't exist

### PR DESCRIPTION
**Pull request by cdknorow**
For my use cases, I'm creating multiple model stores within some overall folder /model_store

ie.

/model_store/model_store_1/operat..
/model_store/model_store_2/operat..
/model_store/model_store_3/operat..

This creates the model_store_1 folder if it doesn't exist in the local

### CODE REVIEW

**Comment by nlathia** [comment]
This looks interesting! Out of interest, what motivates creating multiple stores (e.g. `model_store_1`, `model_store_2`) instead of using different domains in the same store?

**Review by nlathia — CHANGES_REQUESTED** [review]
Thanks again for adding this!

I had a bit of a think about this -- the main thing I think it would be worth being explicit about is the difference between these two case:

 "I want a local `modelstore` at path X, and..."
1. I want path X to be created if it is missing;
2. I want `modelstore` to fail if it is missing

With this change, if a `modelstore` user makes a typo in giving their `root_dir` argument, then `modelstore` will _quietly_ create a new directory and work from there. The user could end up with multiple model directories unintentionally and would then have an epic problem merging them together. There's also the possibility that the user has set the env variable `"MODEL_STORE_ROOT_PREFIX"` to something wrong; again, `modelstore` would quietly create a directory there.

(FYI, this is also why `modelstore` doesn't create s3/GCS buckets yet)

So to get the best of both worlds, how about we make this explicit? At the top level, we'd need to amend `from_file_system()` to be:

```
@classmethod
def from_file_system(cls, root_directory: Optional[str] = None, create_directory: bool = False) -> "ModelStore":
```

And then propagate this downwards to `FileSystemStorage`, and only call `os.mkdir()` if `create_directory = True`, but otherwise keep the default (current) behaviour of raising an `Exception`.

**Comment by cdknorow** [comment]
@nlathia  I'll update with your suggestion.

**Comment by cdknorow** [comment]
@nlathia I couldn't really think of a better way to propagate that to add a variable to the class. Let me know what you think.

**Comment by cdknorow** [comment]
@nlathia there are a number of reasons to want different model stores. If there are two different teams or event two different users, I don't want them to use the same model store. 

Some reasons for this are the model store doesn't have access permission, migrations, etc. so it makes life easier to separate them this way.

**Comment by cdknorow** [comment]
I can also handle this externally to the modelstore package, so its not a necessary change for me

**Comment by nlathia** [comment]
Sorry, I haven't had a chance to look at your code here yet - aiming to do that soon!

**Review by nlathia — APPROVED** [review]
Nice work! I'll merge this now

**Comment by nlathia** [comment]
Actually @cdknorow, there are some conflicts on `test_local.py` - do you mind resolving them?

**Pull request merged**
