### PR TITLE
[Feature] Allows user to set the model_id when saving model

### PR DESCRIPTION
**Pull request by cdknorow**

### CODE REVIEW

**Comment by cdknorow** [comment]
- Allows user to set the model_id when they create a new model in the database
- Moves the logic from creating a model uuid out of the storage component and up the model store component for a more logical flow
- Adds a model exist exception which is raised if the domain/model_id combination already exists in the database

**Review by nlathia — COMMENTED** [review]
Great stuff! I think this paves the way for having multiple different ways of giving models an ID (e.g. using semantic versioning or other approaches too).

Two main questions/thoughts:

1. I recently added in a `DomainNotFoundException`

- https://github.com/operatorai/modelstore/pull/141

I think that `check_model_exists()` should also explicitly check for this type of error; currently, by returning `False` after a `FilePullFailedException` then we _could_ upload a model with an id that already exists, if the `get_meta_data()` call failed for any other reason than a model not existing or a domain not existing.

2. How will this work with model deletion? Currently, when a model with a specific ID is deleted, its meta data is moved to a specific (reserved) state. 

- https://github.com/operatorai/modelstore/pull/137

That way, if a user attempts to download a model, we can return the right error - `ModelNotFoundException` or `ModelDeletedException`. With this change, if a user uploads a model with ID "123" then deletes it and then uploads a new model with ID "123" then technically the meta data will be out of sync: it will show a model as both being in the deleted state and not being in the deleted state. 

What do you think?

**Comment by nlathia** [comment]
Oh, and I remembered one more thing: I think this needs some constraints on what sort of string is allowed as a model id. 

Specifically, we shouldn't allow ids to have the "/" character, because that will break the path/prefix that we use to store model ids in a domain, so will break things like listing models in a domain. We should also probably not allow characters that can't be used in file names?

**Comment by cdknorow** [comment]
@nlathia I'll think more about your point 1. For point 2, I still do not believe the benefit of having model metadata in a deleted state outweighs the complexity of managing that sort of feature. 

In this case, it causes some weird cases with create ->delete->create again and I do not see an intuitive solution managing that. If the intention with the deleted metadata is to log deleted models, why not append to a log file when they delete a model?

**Comment by nlathia** [comment]
@cdknorow I think we can get it to work! Here's how:

1. A user uploads a model, giving it id X;
2. They delete the model, which sets it to state `ReservedModelStates.DELETED`;
3. If they try to retrieve it now, they will get a `ModelDeletedException`;
4. If they upload a new model, giving it id X, then all we need is an extra call to `self.storage.unset_model_state(domain, model_id, ReservedModelStates.DELETED)` to be allowed (it is [currently not allowed](https://github.com/operatorai/modelstore/blob/main/modelstore/storage/blob_storage.py#L264-L267)); but usually unsetting a model state is a no-op if the model was never set to that state to begin with
5. Then their new model with id X will not be in state deleted anymore, and the model will not appear if they try to list deleted models

Did I miss anything?

**Comment by nlathia** [comment]
@cdknorow 👋 I have some time this weekend, so am going to merge this and work on the points we discussed above in separate PRs - so that this can be released with the next version of `modelstore`. Thanks for your contributions 🙌

**Pull request merged**
